kind: pipeline
type: docker
name: Build and test server

platform:
  os: linux
  arch: amd64

steps:
  - name: install dependencies
    image: node:lts-alpine
    commands:
      - yarn install
  
  - name: lint
    image: node:lts-alpine
    commands:
      - yarn lint

  - name: build
    image: node:lts-alpine
    commands:
      - cp .env.example .env
      - yarn build

---
kind: pipeline
type: ssh
name: Deploy to staging

server:
  host:
    from_secret: staging_host
  user:
    from_secret: staging_username
  ssh_key:
    from_secret: staging_key

trigger:
  branch:
    - staging

steps:
  - name: checkout and pull
    commands:
      - git checkout staging
      - git pull

  - name: deploy
    commands:
      - docker-compose down
      - docker-compose build service
      - docker-compose up -d
  
---
kind: pipeline
type: ssh
name: Deploy to production

server:
  host:
    from_secret: prod_host
  user:
    from_secret: prod_username
  ssh_key:
    from_secret: prod_key

trigger:
  branch:
    - master

steps:
  - name: checkout and pull
    commands:
      - git checkout master
      - git pull
  - name: deploy
    commands:
      - docker-compose down
      - docker-compose build service
      - docker-compose up -d