version: '3.8'

services:
  service:
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    image: convenio:latest
    volumes:
      - service-logs:/root/convenio-server/logs
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: convenio
      POSTGRES_PASSWORD: convenio
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database/.:/docker-entrypoint-initdb.d

volumes:
  postgres: ~
  service-logs:
