version: '3.7'
services:
  postgres-db:
    container_name: postgresql
    image: postgres:12.1-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~