version: '3.8'
services:
  service:
    container_name: convenio
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    image: convenio:latest

  postgres-db:
    container_name: postgresql
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~