apiVersion: apps/v1
kind: Deployment
metadata:
  name: convenio-server-deployment
spec:
  selector:
    matchLabels:
      app: convenio-server
  template:
    metadata:
      labels:
        app: convenio-server
    spec:
      containers:
        - name: convenio-server
          image: convenio:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
